### ISSUE TITLE
Question SCTE35

### ISSUE THREAD

**Issue by ctaity** [ut0mt8/nginx-rtmp-module#15]
You implemented cuepoints and or SCTE35 signals in this repo?

**Comment by ut0mt8** [comment]
Yes absolutely. This is documented here https://github.com/ut0mt8/nginx-rtmp-module/blob/dev/DAI.md.

This is with this code that we handled DAI during the 2018 Fifa worldcup at work.
I should had negotiates  a percentage of AD revenue ;)

**Comment by ctaity** [comment]
Lol, no problem, percentage of 0 is 0 for now. Its a project for Argentina.  
Is only dash for now ? Can you paste a example config of nginx using DAI. I dont have a problem to move to dash. Now i am using HLS.

**Comment by ut0mt8** [comment]
Yep but for me I would have been billionaire :) 
It's only for dash for now. Note it has been tested only with Elemental transcoder.

**Comment by ctaity** [comment]
ok no problem , i will test with ericson transcoder, i work tvpublica argentina, public tv channel of Argentina, i can access multiple transcoders to test,

**Comment by ut0mt8** [comment]
It will be interesting. You certainly have to modify some code in the dash part. 

function
ngx_rtmp_dash_on_cuepoint_scte35
or 
ngx_rtmp_dash_on_cuepoint
