### ISSUE TITLE
time_iso8601 variable not available

### ISSUE THREAD

**Issue by brain64bit** [ut0mt8/nginx-rtmp-module#16]
Do you have any suggestion for my issue?

## Expected Behavior
`time_iso8601` available in nginx rtmp module

## Actual Behavior
Variable `time_iso8601` not available in rtmp module
```
sudo /usr/local/nginx/sbin/nginx -t
nginx: [emerg] unknown variable "time_iso8601" in /usr/local/nginx/conf/nginx.conf:53
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

## Steps to Reproduce the Problem

  1. I use `time_iso8601` as part of logging properties
  2. `time_iso8601` used in `log_format` directive
```
rtmp {
   log_format rtmpnginxjson escape=json '{'
	'"@timestamp":"$time_iso8601",'
	'"component":"my_rtmp_app",'
	'"type":"nginxrtmpaccess",'
	'"hostname":"localhost",'
	'"ip":"0.0.0.0",'
	'"client_ip":"$remote_addr",'
	'"connection_number":"$connection",'
	'"application_name":"$app",'
	'"stream_name":"$name",'
	'"command":"$command",'
	'"bytes_sent":"$bytes_sent",'
	'"bytes_received":"$bytes_received",'
	'"session_time":"$session_time",'
	'"session_readable_time":"$session_readable_time",'
	'"msec":"$msec"'
	'}';
    server {
    access_log /usr/local/nginx/logs/rtmp-access.log rtmpnginxjson;
    listen 1935;
    chunk_size 4096;

    application ingest {
            allow play 127.0.0.1;
      live on;
      meta on;

            exec /usr/local/bin/ffmpeg -i "rtmp://localhost:1935/$app/$name timeout=5" -xerror
            -pix_fmt yuv420p -c:v libx264 -tune zerolatency -x264opts keyint=60:min-keyint=60:no-scenecut:bframes=3:b-adapt=2:ref=3:crf=27:vbv-maxrate=413:vbv-bufsize=375 -s 416x240 -profile:v high -preset faster -b:a 96k -c:a libfdk_aac -sws_flags bilinear -f flv rtmp://localhost:1936/hls/${app}_${name}_lowest
      ;
      
          }
  }
}
```
  3. Test nginx configuration

## Specifications

  - Nginx version: 1.8.1
  - Nginx rtmp module: https://github.com/ut0mt8/nginx-rtmp-module/commit/f0ea62342a4eca504b311cd5df910d026c3ea4cf
  - Compilation options: `./configure --prefix=/usr/local/nginx --with-file-aio --with-http_ssl_module --add-module=/tmp/nginx-rtmp-module`

**Comment by ut0mt8** [comment]
Hi,

The documentation is here : https://github.com/arut/nginx-rtmp-module/wiki/Directives#log_format.
So no $time_iso8601.  Honestly this a more an upstream problem, and I have no time/plan to look at that. sorry.
