### ISSUE TITLE
[DASH] Shaka fetching root manifest over and over again

### ISSUE THREAD

**Issue by darki73** [ut0mt8/nginx-rtmp-module#20]
Good time of the day,

Encountered an issue with Shaka Player and this module:

1. Module generates quality for low/med/hi
2. All directories created as they should and files are there
3. Shaka always requesting root manifest

**Nginx Config**
```
user nginx;
worker_processes auto;
# error_log /var/log/nginx/debug.log debug;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /live {
            alias /tmp/nginx/dash;
            add_header 'Access-Control-Allow-Origin' '*';
		    add_header Cache-Control no-cache always;
        
        }

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet static/stat.xsl;
        }

        location /static {
            alias /var/www/static;
        }

        location /time {
            add_header 'Access-Control-Allow-Origin' '*';
            return 200;
        }

    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4000;
        ping 30s;
	    notify_method get;
	    notify_update_timeout 10s;
        publish_time_fix on;

        application live {
            live on;

            on_publish http://app.local/api/stream/start;
            on_publish_done http://app.local/api/stream/stop;
            on_update http://app.local/api/stream/update;

            exec ffmpeg -i rtmp://localhost:1935/live/$name
                -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv -g 30 -r 30 -s 1280x720 -preset superfast -profile:v baseline -vsync cfr rtmp://localhost:1935/dash/$name_hi
                -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 1000k -f flv -g 30 -r 30 -s 854x480 -preset superfast -profile:v baseline -vsync cfr rtmp://localhost:1935/dash/$name_med
                -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 750k -f flv -g 30 -r 30 -s 640x360 -preset superfast -profile:v baseline -vsync cfr rtmp://localhost:1935/dash/$name_low;
        }

        application dash {
            live on;
		    dash on;

            dash_repetition on;
            dash_fragment 2;
            dash_playlist_length 30;
            dash_cleanup on;
            dash_nested on;
            dash_clock_compensation http_head;
            dash_clock_helper_uri http://live.local/time;
            dash_path /tmp/nginx/dash;

            dash_variant _low bandwidth="878000" width="640" height="360";
            dash_variant _med bandwidth="1128000" width="854" height="480";
            dash_variant _hi bandwidth="2628000" width="1280" height="720" max;
        }

    }
}
```

**And this is the generated manifest**
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:cenc="urn:mpeg:cenc:2013"
    xmlns:mspr="urn:microsoft:playready"
    availabilityStartTime="2019-03-31T23:13:32Z"
    publishTime="2019-03-31T23:13:32Z"
    minimumUpdatePeriod="PT2.046S"
    minBufferTime="PT2.000S"
    timeShiftBufferDepth="P0Y00M00DT0H00M08.046S"
    suggestedPresentationDelay="PT5.092S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        startWithSAP="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="30"
        par="16:9">
      <Representation
          id="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_low_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="878000"
          width="640"
          height="360"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_low/$Time$.m4v"
            initialization="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_low/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000" r="2"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_med_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="1128000"
          width="854"
          height="480"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_med/$Time$.m4v"
            initialization="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_med/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000" r="2"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="2628000"
          width="1280"
          height="720"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi/$Time$.m4v"
            initialization="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000" r="2"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        startWithSAP="1"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          bandwidth="125000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi/$Time$.m4a"
            initialization="852efbfca498c8fddc214c2ae2ab0991973d97339df92fab80ab7d570e449a6ec1ec80502d8d9cc97a56d04b2b3e942e94ad07857a48d055ce011f71060c03fd_hi/init.m4a">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000" r="2"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014"
       value="http://live.local/time" />
</MPD>
```

Actually, same goes for VLC, it just cannot play the playlist

**Comment by ut0mt8** [comment]
Seems valid mpd for me. That said the mpd online validator complains about framerate and scaling ?!.
Have you tried with repetition off ?

**Comment by darki73** [comment]
MPD validator says everything is fine, the only thing it complains about is something about hbbtv dvb.

I've turned off repetition, and no players can still play the stream.

With hls, it works fine, it fetches the master manifest, chooses the resolution and then fetches data from the folder for appropriate resolution.

With dash, it fetches the master manifest, then fetches it again, then again, then again, and so on. So it seems like it cannot decide which bandwidth to use.

Same goes for ALL players, the access logs on nginx server clearly state that all players do the same thing, like exactly the same behavior.

Even VLC, which was able to recover in my previous configuration (in the issue we were talking about before) now failing to open the stream, it can even go as far as complete system hang while trying to do so.

Only difference i've spotted regarding the "validity" or actual difference is that other "examples" use full paths to the files (init, etc), both goes for HLS and DASH.

**Comment by ut0mt8** [comment]
Do you have any shaka log ? this is indeed strange.

**Comment by darki73** [comment]
Shaka is not even spitting any logs (means that it feels like manifest is valid), it loads manifest, everything is fine, but
1. It is not starting to play
2. It keeps fetching the manifest from the server over and over

I've even tried to disable ABR, to set ABR to 2628kbps to be fetched first (like try to get highest quality first, then do the automatic switching), still the same.

I will switch to the debug version of shaka now and will try to copy full output from the console, just give me 5 minutes to do so.

**Comment by ut0mt8** [comment]
Yes you need to switch to debug version and/or to enable debug in the js. I've already done that in the past. Don't hesitate to ask help on shaka gh, people are really helpful.

**Comment by darki73** [comment]
![Screenshot from 2019-04-01 21-29-47](https://user-images.githubusercontent.com/1318627/55350699-59006780-54c5-11e9-9409-fe763d81d57e.png)

And it will keep spitting out this, and try to fetch manifest until the stream is stopped (well, event reloads the player so)

I guess same goes for VLC, since the MPD request pattern is pretty much the same.

I know it might seem like time sync issue, however, there is 0 changes to the machine since my last posted issue about private/public key, i even set the timezone for the machine to be UTC

**Comment by darki73** [comment]
Even with fix from https://github.com/z411/nginx-rtmp-module it still spits these errors

![Screenshot from 2019-04-01 21-42-36](https://user-images.githubusercontent.com/1318627/55351460-1a6bac80-54c7-11e9-8602-3d4aff17c1cb.png)

**Comment by ut0mt8** [comment]
Do you have a recent manifest ?  it really look like a timing problem.

**Comment by darki73** [comment]
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:cenc="urn:mpeg:cenc:2013"
    xmlns:mspr="urn:microsoft:playready"
    availabilityStartTime="2019-04-01T18:43:39Z"
    publishTime="2019-04-01T18:43:39Z"
    minimumUpdatePeriod="PT2.046S"
    minBufferTime="PT2.000S"
    timeShiftBufferDepth="P0Y00M00DT0H00M06.213S"
    suggestedPresentationDelay="PT5.092S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        startWithSAP="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="30"
        par="16:9">
      <Representation
          id="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_low_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="878000"
          width="640"
          height="360"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_low/$Time$.m4v"
            initialization="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_low/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="533"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_med_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="1128000"
          width="854"
          height="480"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_med/$Time$.m4v"
            initialization="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_med/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="400"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="2628000"
          width="1280"
          height="720"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi/$Time$.m4v"
            initialization="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="167"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        startWithSAP="1"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          bandwidth="125000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi/$Time$.m4a"
            initialization="808b235d0afa85a6f3b31f5aa8b95b750eb85deac92b3149e2542e1f021950dbc75d0adc2cd024ff1a9008e1d0b6e0d3fe41e4cd31a95de2471a53f0992bcdb7_hi/init.m4a">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="167"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014"
       value="http://live.local/time" />
</MPD>
```

**Comment by ut0mt8** [comment]
Is 2019-04-01T18:43:33 + 6s is correct ? btw try to remove UTC timing also.

**Comment by darki73** [comment]
Well, it was 2019-04-01 21:43:33 in Moscow, so Moscow is +3, UTC is Moscow -3, so ye, perfectly correct.

Where these 6 seconds are coming from i have no idea, but as far as i know, it is sort of "looking into the future", with fragments of 2 seconds length, it should provide 3 fragments to look forward.

I will  try to remove UTC timing now

**Comment by darki73** [comment]
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:cenc="urn:mpeg:cenc:2013"
    xmlns:mspr="urn:microsoft:playready"
    availabilityStartTime="2019-04-01T18:50:37Z"
    publishTime="2019-04-01T18:50:37Z"
    minimumUpdatePeriod="PT2.046S"
    minBufferTime="PT2.000S"
    timeShiftBufferDepth="P0Y00M00DT0H00M10.179S"
    suggestedPresentationDelay="PT5.092S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        startWithSAP="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="30"
        par="16:9">
      <Representation
          id="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_low_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="878000"
          width="640"
          height="360"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_low/$Time$.m4v"
            initialization="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_low/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="2000"/>
             <S t="8046" d="2000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_med_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="1128000"
          width="854"
          height="480"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_med/$Time$.m4v"
            initialization="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_med/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="2000"/>
             <S t="8046" d="2000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation
          id="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi_H264"
          mimeType="video/mp4"
          codecs="avc1.42c01f"
          sar="1:1"
          bandwidth="2628000"
          width="1280"
          height="720"
          >
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi/$Time$.m4v"
            initialization="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi/init.m4v">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="2000"/>
             <S t="8046" d="2000"/>
             <S t="10046" d="133"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        startWithSAP="1"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          bandwidth="125000">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi/$Time$.m4a"
            initialization="7094219078cc024f2a8a824b6ea29384f3b18c7f84ccfb7f1eeab1a3ba2f1d1e69a76f49f6052285d8041599214c3033e72a19c262d9dbc943fd03d4b012984a_hi/init.m4a">
          <SegmentTimeline>
             <S t="0" d="2046"/>
             <S t="2046" d="2000"/>
             <S t="4046" d="2000"/>
             <S t="6046" d="2000"/>
             <S t="8046" d="2000"/>
             <S t="10046" d="133"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
![Screenshot from 2019-04-01 21-51-00](https://user-images.githubusercontent.com/1318627/55351926-4b001600-54c8-11e9-9e67-3383423781d4.png)

**Comment by ut0mt8** [comment]
that really look ok. on the network tab of the debugger what chunck the player are trying to download ?

**Comment by ut0mt8** [comment]
Do you have a public version of your mpd ?

**Comment by darki73** [comment]
![Screenshot from 2019-04-01 21-53-54](https://user-images.githubusercontent.com/1318627/55352072-afbb7080-54c8-11e9-85cb-0a6a36bd2872.png)

It is running on the localhost, and i don't have static IP

**Comment by ut0mt8** [comment]
hum also if I remind correctly shaka need https.

**Comment by darki73** [comment]
Localhost considered to be "safe" location for any Google product, so they dont usually require HTTPS, plus, no errors are given in regards of insecure connection.

Give me a minute or two, i will setup Ngrok.

Oh well, it just wont proxy the localhost to the outside network for some reason (even with disabled firewall)

**Comment by ut0mt8** [comment]
Really take an aws instance or whatever. It will cost you quasi nothing and save precious time.

**Comment by darki73** [comment]
Waiting for GCE to be activated, AWS for some reason still asks me to verify my information (account is 3 years old, with all the data submitted like 3 years ago)

**Comment by ut0mt8** [comment]
gcp is a good choice :)

**Comment by darki73** [comment]
Never mind,  right now it just dont want to write any files, even though the directories are under correct user and group, stream is visible on the stats page, however, directory for files is empty

**Comment by darki73** [comment]
Narrowed down the issue to the exec command, neither 0.0.0.0/127.0.0.1/server_ip is working, hence no files are created

**Comment by darki73** [comment]
Well, i guess i will just drop that idea and will play some games, not worth it. So many issues around this module, one one machine it is working, but breaking up and produces something which cannot be read by the players, on the other machine (yes, GCE is also Ubuntu and also 18.10) the simple **exec** command is not working (even with the .sh workarounds, yes, there are dozens of issues with that problem). And funny thing is, even with the debug enabled, there are 0 usefull logs, it doesnt event saying why **exec** is failing.

However, when i try to **"exec"** myself, i mean just to run this command manually, it creates 4 (1 ingest + 3 adaptive) streams on the **/stats** page, 3 folders in the directory, but no master manifest. What kind of sorcery is this

**Comment by darki73** [comment]
< rage-off >
**Here is the stats page:** https://35.246.132.240/stat  
**Here is the MPD file:** https://35.246.132.240/live/live_1_Nx39vmWYAN8tK7s1LDrRGR6N9TAgXyUPJwS69hd8hJdyRDzX.mpd

Sorry for raging, it is been too long since i am trying this out (built docker container, much easier to "avoid" machine specific issues)

**P.S.** updated container to support HTTPS

**Comment by darki73** [comment]
I will shut it down in about 10 minutes, so please, let me know when you will be available so i can start the stream again

**Comment by darki73** [comment]
Well, no idea, here are the specs:

**Google Cloud Engine:**
![Screenshot from 2019-04-02 01-48-09](https://user-images.githubusercontent.com/1318627/55364471-6b8c9800-54e9-11e9-9e61-184f1aa21877.png)
![Screenshot from 2019-04-02 01-49-41](https://user-images.githubusercontent.com/1318627/55364518-9e369080-54e9-11e9-8b24-cc31319e1d17.png)

**Local Machine:**
![Screenshot from 2019-04-02 01-50-17](https://user-images.githubusercontent.com/1318627/55364533-b1496080-54e9-11e9-84b3-cbed2ace7144.png)
![Screenshot from 2019-04-02 01-51-03](https://user-images.githubusercontent.com/1318627/55364560-cd4d0200-54e9-11e9-9b1c-f7ba28b767ce.png)


**Common:**
1. **OS:** Ubuntu 18.10 with latest updates
2. **Network:** 1Gbps
3. **Docker:** 18.09.4
4. **Docker Image:** Compiled on local machine (own image, not the public ones)

And here is the thing, stream either lags or not starting at all (with all errors mentioned since the beginning of this issue) on local machine, but working just fine on the GCE

Both containers are started with the same command:
```docker run -it -p 1935:1935 -p 80:80 -p 443:443 --rm rtmp-docker```
Both containers using the same **nginx.conf** file.  

One is working, one is not (local one). So in order to use ffmpeg you have to have Xeon???? Seems like i9 is not an option

**Comment by darki73** [comment]
**In addition to previous message**

According to massive L3 cache, it is stripped down E5-2699v4 with 22 cores and 44 threads (stripped down to 4 core 8 threads) running at 2.2 Ghz. Well, i would agree that the "full" version of that CPU will be much better than my i9, even when comparing **bogomips** (yes, i know, it is in the name, you cannot really rely on it), mine is a bit faster with more cores/threads (twice to be precise).

Yet, nginx on this machine (well, in docker) is still not able to perform, however GCE is working just fine (even with pinging my system about the events start/stop/update with 45ms delay, while local is 0.043ms).

Do you have any idea on what might be wrong in here? 

**P.S.** also, is there any relation between **dash_fragment** and **keyframe** interval? Given that the source video is encoded with keyframe of 2, what the fragment length should be set to? i guess this is the reason my streams are not working properly.

(OBS - Open Broadcaster Software, provides the option to set the keyframe, and then the stream will use the keyframe set in OBS, so in Twitch case, it is 2, what the fragment and playlist length should look like)

**P.P.S**
I guess i've found the source of the problem, for some reason, chunks are not generated the way they should be, hence the interruption in streams
![Screenshot from 2019-04-02 09-19-12](https://user-images.githubusercontent.com/1318627/55380308-803c5080-5528-11e9-8577-9c9b6555d4f6.png)
(I've waited for 2 seconds between each _ls_ and here is what i've got)

And also pretty strange **PUBLISH** pattern here (look at the time of the request, and number of seconds published)
![Screenshot from 2019-04-02 09-21-15](https://user-images.githubusercontent.com/1318627/55380412-c5f91900-5528-11e9-9d2b-8954edd675ed.png)

**Comment by ut0mt8** [comment]
I don't really understand the status. What is sure is that your proc is far sufficient for producing dash from rtmp. Actually this is not very cpu intensive process, only reordering bytes.

**Comment by darki73** [comment]
Status is pretty much the https://github.com/ut0mt8/nginx-rtmp-module/issues/20#issuecomment-478846912 the **P.P.S** part

**Comment by darki73** [comment]
Issue has been found:

1. **on_update** callback triggers **_"really"_** multiple times
2. Since we are awaiting for this callback to complete, we are introducing "latency" to the  stream processor
3. When there is a latency, there are stream breakups
4. So either we need to introduce new "async" trigger, something like "on_update_async" to asynchronously send data to server, for example, for stream information collection (bits send/received, resolution, bitrate, etc), or just do nothing, since for most it is not of a big deal to miss such data

So really, it should be pretty easy to implement, however, i am nowhere near to knowing C (especially in the context of software i've never worked with), the only thing needed to accomplish such behavior is to simply send the request and forget about it,no need to wait for the result of the request.

Think of it as UDP in http, request is sent but 0 *ucks given if it arrived or not.

I know i am asking too much, and already took up alot of your time, but do you think you can look into this?

**P.S.** If you really gonna help me with this, i might have a name for that event, **on_stats_update** =)
**P.P.S** Just to make it clear, not just wondering around, actually trying to solve it myself...
**P.P.P.S** This is actually blocking (synchronous) executing, no?
![Screenshot from 2019-04-04 04-06-58](https://user-images.githubusercontent.com/1318627/55522803-2efaa100-568f-11e9-89f5-1cd418a5f955.png)

**Comment by ut0mt8** [comment]
Hum interresting. I haven't played with this features so I cannot comment. Cool you find the why.
