### ISSUE TITLE
[DASH] Is it possible to pass "source" quality

### ISSUE THREAD

**Issue by darki73** [ut0mt8/nginx-rtmp-module#21]
So, the title states it, is it possible to parse source quality without encoding?

Obviously, i have no idea on which bitrates and framerates use might use, so i cannot simply define the bitrate in the dash_variant, yet i can simply "pass" the stream through without encoding.

**Comment by ut0mt8** [comment]
Re,

Not really. That said the bitrate is bit informative for the player. It doesn t need to be exact.
