### ISSUE TITLE
Merge fix for broken compile on vanilla Debian 9.

### ISSUE THREAD

**Issue by ghost** [ut0mt8/nginx-rtmp-module#4]
Hi,

Any chance you could merge this fix into your code?

https://github.com/superp00t/nginx-rtmp-module/commit/54c6dd2234468df025a3a1e168e80560ec003d3d

The current compile is broken on a vanilla Debian 9 setup as per this bug:

https://github.com/arut/nginx-rtmp-module/issues/791

**Comment by ut0mt8** [comment]
Sure it was an easy one.
Expect this on august cause I'm in vacation without a proper internet connexion.

**Comment by ghost** [comment]
There's a more comprehensive fix here:

https://github.com/arut/nginx-rtmp-module/commit/04f0ab97ac61d181dbfdaa5299412fc3064e95a3

The original patch I referenced apparently breaks support for earlier OpenSSL versions :-(

- Matt

**Comment by ut0mt8** [comment]
I merge from the last sergey branch, the patch is now included.
