### ISSUE TITLE
Incorrent format for printing cuepoint details

### ISSUE THREAD

**Issue by ilyaevseev** [ut0mt8/nginx-rtmp-module#5]
All "%ui" in "onCuepoint write emsg" call must be replaced to "%uD" because all printed values are 32bit.

See also "supported formats" section in nginx/src/core/ngx_string.c

**Comment by ut0mt8** [comment]
Good catch. As soon as I got a real internet cnx I will fix it.
Did you use this patch / cuepoint ? I would be happy to share use case and problem.
(at work we are almost ready to use it for your principal live stream 👍 )

**Comment by ut0mt8** [comment]
Fixed.
