### ISSUE TITLE
scte35 inband supports.

### ISSUE THREAD

**Issue by ghost** [ut0mt8/nginx-rtmp-module#8]
I tried to use scte35 inband feature this fork. But it seems this doesnt work by default. Can you share me some stream that having scte35 event inside, or how can I make it works. 
Thanks in advance
Tam

**Comment by ut0mt8** [comment]
What did you try to achieve ? 
It sure need a video flow with scte marker inside, otherwise it do ... nothing.
The only equipment I qualified is AWS Elemental Live server (both onCuepoint and onCuepointScte35). It may work with other equipment but sure need some adjustment.

**Comment by ghost** [comment]
well. I'm developing the stream with scte35 by myself, so maybe there's something wrong with my implemetation. I'll deploy aws elemental server to verify it. One more thing. I believe you're an expert on this. Do you think is it feasible if I want to develop a module that having capable of inserting scte35 marker. Can you recommend some open source that I can use for this purpose.
Thanks,
Tam

**Comment by leandromoreira** [comment]
@ut0mt8 does this module carries to the TS the scte35 messages from rtmp?

**Comment by ut0mt8** [comment]
@leandromoreira no it only work for dash. That said it will not be too difficult to add the support for HLS. Note that in the case of HLS, scte35 message must be in the manifest (out of band signalling).

**Comment by leandromoreira** [comment]
thanks @ut0mt8 

yes I'm looking specifically for hls scte35 messages =) can you point me to the dash implementation or where I can get inspiration to try implment hls?

this features implies that the original RTMP passes this scte message, right? in this case if one uses ffmpeg to generate ABR is it valid? (I suppose ffmpeg also just repass the track scte)

**Comment by ut0mt8** [comment]
First of all you need an encoder that carries scte35 message from the source (mpeg 2 ts from SDI, or other) to RTMP. It seems that ffpmeg have some king of support for scte but I didn't play with it myself.  My only work case ,as I mentioned it in the doc, is embedded scte35 markers in RTMP from Elemental Live server. 

Unfortunately the scte35 messages in RTMP are not standard. It depend both of the method used and the encoder. And to make things more funny they are in old binary serialisation format called AMF (from Adobe in the RTMP standard). So you certainly have to deal with binary/hexa at some point.

In my code you can look at the ngx_rtmp_dash_on_cuepoint_scte35 function in the dash/ngx_rtmp_dash_module.c file for decoding such event. After you have catched the event you "just have" to write it as is in the m3u8 manifest. This is doable but I have definitively not the time to do it (I'm now a manager; youhou).

Some links that can be interesting : 

- https://gist.github.com/satori99/2cb06938bfe8532ecc00e60906509052
- https://www.reddit.com/r/ffmpeg/comments/ale4zj/insert_scte35_ad_markers_in_hls_feed/

Hope it helps.

**Comment by leandromoreira** [comment]
@ut0mt8 thanks for the tips/references quick question, do you split the segments even further based on their scte35 cue-out?

Let's say our segments are fragmented every 6s but my ad was signaled at 4th second, in theory I should break the 6s segment in two new segments (in dash create a new period...) one being 4s and the ad start with 2s (starting with the IDR).

**Comment by ut0mt8** [comment]
Nope, I didn't follow this specification of splitting segments with period. In fact I didn't touch the manifest at all except for adding <InbandEventStream> tag. So that's it I add the ad marker *inband* aka inside the mp4 segment. It work at least for us in dashjs and shaka. (and if I remember correctly we didn't have much success with the out-of-band method, elemental delta did that, but players weren't doing well at the time)

**Comment by leandromoreira** [comment]
thanks I appreciate your time and work =) happy holidays. I'm evaluating some packagers to deal with scte35 and this is great source of knowledge.

**Comment by ut0mt8** [comment]
I'll be curious of your choice and the market of live packager cause three years earlier it was a bit the desert.

Unfortunately I'm not in the video anymore (it was a great time for me), now I'm engineering manager of a data eng team (interesting as well, kafka, flink, spark, this kind of stuffz).

TY and happy holidays too.
