### ISSUE TITLE
Support with WebM

### ISSUE THREAD

**Issue by usama-dev** [ut0mt8/nginx-rtmp-module#9]
Hey, 

How can I use different codec like vp9 for transcoding because when I use the following command:

`ffmpeg -i rtmp://localhost:1935/$app/$name
-c:v libvpx-vp9 -f webm rtmp://localhost/dash/$name_dash`

The ffmpeg starts running in the backgroud but the /dash directory remains empty.

**Comment by ut0mt8** [comment]
Unfortunately only h264 is supported on nginx-rtmp module.
